# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Zacc/Documents/8085/8085.cache/wt [current_project]
set_property parent.project_path C:/Users/Zacc/Documents/8085/8085.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Zacc/Documents/8085/8085.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/new/8bit_Register.vhd
  C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/new/accumulator.vhd
  C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/new/addr_data_buffer_unit.vhd
  C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/new/address_latch.vhd
  C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/new/alu.vhd
  C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/new/controller.vhd
  C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/new/counter.vhd
  C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/new/demux.vhd
  C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/new/instruction_reg.vhd
  C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/new/internal_addr_latch.vhd
  C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/new/mux.vhd
  C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/new/ram.vhd
  C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/new/register_block.vhd
  C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/new/register_select_unit.vhd
  C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/new/seven_segment_driver.vhd
  C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/new/temp_reg.vhd
  C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/new/tri_buffer.vhd
  C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/new/main.vhd
}
read_ip -quiet C:/Users/Zacc/Documents/8085/8085.srcs/sources_1/ip/u_ila_0/u_ila_0.xci
set_property used_in_synthesis false [get_files -all c:/Users/Zacc/Documents/8085/8085.srcs/sources_1/ip/u_ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Zacc/Documents/8085/8085.srcs/sources_1/ip/u_ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Zacc/Documents/8085/8085.srcs/sources_1/ip/u_ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Zacc/Documents/8085/8085.srcs/sources_1/ip/u_ila_0/u_ila_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Zacc/Documents/8085/8085.srcs/constrs_1/new/Basys3.xdc
set_property used_in_implementation false [get_files C:/Users/Zacc/Documents/8085/8085.srcs/constrs_1/new/Basys3.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top main -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
